server:
  port: 8888
spring:
  #  profiles:
  #    active: dev
  application:
    name: un
  mvc:
    throw-exception-if-no-handler-found: true
  ##    pathmatch:
  ##      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    serialization:
#      write-dates-as-timestamps: false
  #循环依赖
  main:
    allow-circular-references: true
---
# 设置算法片段
approve:
  workerId: 1
  datacenterId: 1
---
# redis配置
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 7
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

---
# db配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: default
      druid:
        filters:
        testWhileIdle: true
        validationQuery: select 1
      datasource:
        #默认的bi配置
        default:
          url: jdbc:mysql://8.142.109.85:3306/unexamine2?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true&allowPublicKeyRetrieval=true
          username: un
          password: password
---
# mapper配置
mybatis-plus:
  mapper-locations: classpath:xml/*.xml
---
# satoken配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
---
# tianyancha配置
tianyancha:
  token: 44444444444444444444
  url: http://open.api.tianyancha.com/services
